# Generated by Django 6.0.7 on 2026-07-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('reader', 'Reader'), ('admin', 'Admin')], default='reader', max_length=20),
        ),
    ]
