# Generated by Django 6.0.7 on 2026-07-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagPostJunction',
            new_name='PosTagJunction',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creaed_at',
            new_name='created_at',
        ),
    ]
