# Generated by Django 6.0.7 on 2026-07-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PosTagJunction',
            new_name='PostTag',
        ),
    ]
