# Generated by Django 6.0.7 on 2026-07-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='commented_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='published_date',
        ),
    ]
